DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    gender CHAR(1) NOT NULL,
    age INTEGER NOT NULL
);

DROP TABLE IF EXISTS admins;
CREATE TABLE admins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

DROP TABLE IF EXISTS venues;
CREATE TABLE venues (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR UNIQUE NOT NULL,
    multiplier INTEGER NOT NULL DEFAULT 100, 
    capacity INTEGER NOT NULL,
    place VARCHAR NOT NULL,
    location VARCHAR NOT NULL
);

DROP TABLE IF EXISTS shows;
CREATE TABLE shows (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    rating INTEGER NOT NULL DEFAULT 0, 
    tags VARCHAR NOT NULL,
    price INTEGER NOT NULL,
    timing VARCHAR NOT NULL,
    venue_id INTEGER NOT NULL,
    FOREIGN KEY(venue_id) REFERENCES venues(id) 
);